cmd: "cd Release; . /etc/profile.d/modules.sh; module load mpi/openmpi/1.10.4; make -j4"
name: "feaconduct Release"
targets:
    "feaconduct Debug":
        cmd: "cd Debug; . /etc/profile.d/modules.sh; module load mpi/openmpi/1.10.4; make -j4"
    "configure feaconduct Release":
        cmd: "mkdir -p Release; cd Release; . /etc/profile.d/modules.sh; module load mpi/openmpi/1.10.4 boost; cmake -DBOOST_ROOT=/opt/boost/1.58.0 -DCMAKE_BUILD_TYPE=Release -DLIBMESH_SRC_PATH=/home/tim/thirdparty/libmesh -DEIGEN_INCLUDE_PATH=/home/tim/thirdparty/eigen -DPETSC_SRC_PATH=/home/tim/thirdparty/petsc .."
    "configure feaconduct Debug":
        cmd: "mkdir -p Debug; cd Debug; . /etc/profile.d/modules.sh; module load mpi/openmpi/1.10.4 boost; cmake -DBOOST_ROOT=/opt/boost/1.58.0 -DCMAKE_BUILD_TYPE=Debug -DLIBMESH_SRC_PATH=/home/tim/thirdparty/libmesh -DEIGEN_INCLUDE_PATH=/home/tim/thirdparty/eigen -DPETSC_SRC_PATH=/home/tim/thirdparty/petsc .."
